image::../images/logos/logo-braxen.svg[alt="Braxen logo", width="200", float="right"]
= Braxen 1.0 Documentation

:author: Swedish Agency for Accessible Media (MTM)
:license: CC BY 4.0
:url-license: https://creativecommons.org/licenses/by/4.0/legalcode.en
// Local variables
:braxen: Braxen 1.0
:mtm-1st: Swedish Agency for Accessible Media (MTM)
:mtm: MTM
:voc-sbtal: Språkbanken Tal
:field: Field
:field-0: Orthography
:field-0-full: {field} 0: {field-0}
:field-1: Pronunciation
:field-1-full: {field} 1: {field-1}
:field-2: Part of speech and morphology
:field-2-full: {field} 2: {field-2}
:field-3: Language code
:field-3-full: {field} 3: {field-3}
:field-16: Case
:field-16-full: {field} 16: {field-16}
:field-26: ID
:field-26-full: {field} 26: {field-26}

:format-base: Base


// 1st para wIll be formatted as abstract by default
{braxen} is a Swedish pronunciation dictionary for speech technology, 
developed by {mtm-1st}. 
It is made public in cooperation with {voc-sbtal}.

== Structure

The underlying data for {braxen} is a straight-forward two-dimensional table, with 
entries for full-form words, abbreviations, and acronyms, and 
columns ({field}s) for various attributes of these entries.

=== Entries

An entry in {braxen} is defined by its full-form orthography,
and several entries with the same orthography is permissable, but 
only if they differ in another field.

=== {Field} structure

An entry in {braxen} consists of 27 fields. 
In its raw, tab-separated form, each field occupies a column, and 
the order is meaningful, so that columns 0 to 26 have semantics. 

In the current version, only a subset of these fields are shared publicly.
The structure of the public dictionary remains the same, hwoever, 
resulting in a number of empty columns
(see <<_appendix_a_field_information>>).

The most important fields are described in the following.

== {field-0-full}

The orthography field shows the spelling of the word. 

A considerable amount of pragmatics goes into the orthography field. 
For example, the most frequent casing is used, as 
different casings can sometimes indicate different pronunciations (see <<_16_case>>).

.Examples
[cols="1,1,1", options="header"]
|===
| Orthography | Part of Speech | Pronunciation
| björn | Noun | /b j ’oe: rn/
| Björn | Proper name | /b j ’oe: rn/
| BrB | Proper name (abbreviation) | Brottsbalken
| BRB | Proper name (acronym) | B R B
|===

== {field-1-full}

The format for the phonetic-phonological transcriptions covers 
Swedish and common foreign phonemes. 
Here, this fomat is referred to as *{format-base}*.

<<_appendix_b_phoneme_table_base_and_ipa>> provides 
a conversion table between Base and IPA. 
Tools for automatic conversion are included in the
`/p5m/scripts` directory).


.Conversion Tools
[cols="1,1", options="header"]
|===
| Script | Task
| convertBase2IPA.pl | Converts {format-base} to IPA
| convertIPA2Base.pl | Converts IPA to {format-base}
| validateBase.pl | Validates {format-base} transcription
| validateIPA.pl | Validates IPA transcription
|===

Note that the conversion tools are written in Perl.
Using e.g. Docker, they can be used without installing a Perl interpreter.

.Example of validation using Docker
[source,bash]
----
cd /braxen/repo/root
docker run -v "$PWD":/work -it perl -c "/work/p5m/scripts/validate_braxen.pl /work/INFILE /work/
OUTFILE"
----

=== Stress

All {braxen}} words have exactly one main stress, 
which can be either accent 1 or accent 2. 
Words with accent 2 also have secondary stress. 
Stress is marked immediately before the stressed vowel.

.Stress notation examples
[cols="1,1,1", options="header"]
|===
| Stress | Notation | Example (Transcription)
| Main stress, accent 1 | ’ | boll (/b ’o l/)
| Main stress, accent 2 | ” | bollar, dalbana (/b ”o . l ,a r/, /d ”a: l - b ,a: . n a/)
| Secondary stress | , | bollar, dalbana (/b ”o . l ,a r/, /d ”a: l - b ,a: . n a/)
|===

=== Boundaries

Word boundaries allow multiple main stresses within an expression. 

.Word boundary examples
[cols="1,1,1", options="header"]
|===
| Boundary | Notation | Example (Transcription)
| Word | `|` | berg- och dalbana (/b ’ae rj | ’o: | d ”a: l - b , a: . n a/)
| Compound | `-` | dalbana (/d ”a: l - b ,a: . n a/)
| Morpheme* | `~` | transalpin (/t r a n s ~ a l . p 'i: n/)
| Syllable | `.` | alpin (/a l . p ’i: n/)
|===

*The morpheme boundary is optional but can be included when needed.

=== /e/ Sounds

{braxen} distinguishes between four /e/ sounds, 
mainly reflecting a central Swedish pronunciation.

./e/ pronunciations
[cols="1,2,2", options="header"]
|===
| Phoneme | Description | Example (Transcription)
| `e` | Semi-open /e/ sound | sett (/s ’e t/)
| `ä` | Semi-open /e/ sound (dialectal variation) | sätt (/s ’ä t/)
| `eh` | Before stressed syllable in unstressed, open syllable | betona (/b eh . t ’u: . n a/)
| `ex` | Schwa, used in unstressed syllables | bollen (/b ’o . l ex n/)
|===

=== Xenophones (foreign speech sounds)

The phoneme inventory includes foreign phonemes, 
so-called xenophones, primarily from English.

== {field-2-full}

Part of speech and morphological data largely follow 
the Stockholm-Umeå Corpus (SUC) principles (Gustafson-Capková & Hartmann, 2006). 
The *UO* (foreign word) tag is rarely used, as 
language codes indicate whether a word is Swedish or foreign.

Different parts of speech or morphological information for 
the same orthographic form can lead to different pronunciations:

.Part of speech and pronunciation examples
[cols="1,1,1", options="header"]
|===
| Orthography | Part of Speech | Pronunciation
| slutet | NN | /s l ’uu: . t ex t/
| slutet | JJ | /s l ”uu: . t ,ex t/
| planet | NN UTR SIN IND NOM | /p l a . n ’e: t/
| planet | NN NEU SIN DEF NOM | /p l ’a: . n ex t/
|===

<<_appendix_c_part_of_speech>>
provides a list of selected PoS codes.

== {field-3-full}

Language codes follow the ISO 639-2 standard (Library of Congress, 2017). 
The language code indicates the intended language of the orthography at 
the time of pronunciation creation.

.Examples of different language codes for the same word
[cols="1,1,1", options="header"]
|===
| Orthography | Language Code | Pronunciation
| Anne | swe | /’a n/
| Anne | eng | /’ae n/
|===

<<_appendix_d_language_codes_examples>> 
provides a list of selected language codes.

== {field-16-full}

This field indicates case sensitivity:
- `1` = Case-sensitive
- `0` = Not case-sensitive

== {field-26-full}

An internal identifier for each entry.

== References

* Gustafson-Capková, S., & Hartmann, B. (2006). *Manual of the Stockholm Umeå Corpus version 2.0*.
* Library of Congress. (2017). *ISO 639-2 Language Code List*. https://www.loc.gov/standards/iso639-2/php/code_list.php

== Appendix A: Field Information

Bold fields are shared publicly.

[cols="1,2,2", options="header"]
|===
| Field | Name | Example
| 0 | orth | bjärornas
| 1 | pron | b j ”ae: . r ,u . rn a s
| 2 | posmorph | NN UTR PLU DEF GEN
| 3 | lang | swe
| 16 | case | 0
| 26 | id | 0060097
|===

== Appendix B: Phoneme Table (Base and IPA)

[cols="1,1,1", options="header"]
|===
| Base | IPA | Example
| p | p | pil
| i: | iː | sil
| y: | yː | syl
| ä: | ɛː | säl
| ö: | øː | rön
|===

== Appendix C: Part of Speech

Following (Gustafson-Capková & Hartmann, 2006).

[cols="1,2,1", options="header"]
|===
| Tag | Description | Example
| AB | Adverb | inte
| JJ | Adjective | glad
| NN | Noun | pudding
| VB | Verb | kasta
|===

== Appendix D: Language Codes (Examples)

[cols="1,1", options="header"]
|===
| Code | Language
| swe | Swedish
| eng | English
| fre | French
| ger | German
| rus | Russian
|===

